---
title: "Projecting Waffle Pars"
author: "Jackson Rudoff"
date: "8/29/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document outlines my attempts to make a waffle par predictor.

```{r Doing initial tests}

library(pacman)
pacman::p_load(tidyverse, lme4, openxlsx)

#I figure a few variables matter most here: day of the week, season, weather, and historical totals. I'll start off by creating the easy variables.

week_day <- factor(c
                   ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'),
                   levels = c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')) 

weather <- as.factor(c('Stormy', 'Sunny', 'Overcast', 'Drizzling', 'Snow', 'Chilly'))

season <- as.factor(c('Winter', 'Spring', 'Summer', 'Fall'))

special_event <- as.factor(c('Yes', 'No'))

OSU_students <- as.factor(c('Yes', 'No'))

#Gonna do this with fake data first to see how well this will eventually work

cones <- sample.int(250, 84, replace = TRUE)

#Try to make a frame here

test_season <- c((rep(season[2],22)),
                  (rep(season[3],62)))

test_OSU_students <- c((rep(OSU_students[2],66, replace = TRUE)), 
                        (rep(OSU_students[1],18, replace = TRUE)))
test_special_event <- sample(special_event, 84, replace = TRUE)
test_day <- rep(week_day, times = 12)
test_weather <- sample(weather[1:4], 84, replace = TRUE)

x <- tibble(cones, test_day, test_season, test_OSU_students, test_special_event, test_weather)


#Okay so now we can run a basic linear model to find interactions

waffle_test <- lm(formula = cones ~ test_day + test_season + test_weather + test_special_event + test_OSU_students, data = x)
summary(waffle_test)

#See if it predicts


predict(waffle_test, data.frame(test_day = 'Tuesday', test_season = 3, test_weather = 'Sunny', test_special_event = 'Yes', test_OSU_students = 2))




```

```{r Reading in the data}

library(readr)
library(openxlsx)
library(tidyverse)
library(lme4)
library(MASS)

waffle_totals_daily <- read.xlsx("~/Documents/Data Projects/Waffle Project/waffle_totals.xlsx") %>% as_tibble()

weather_data <- read_csv("weather data.csv") %>% as_tibble()

dailytemp <- weather_data$TAVG[88:280]
realdates <- weather_data$DATE[88:280]
dailyprecip <- weather_data$PRCP[88:280]
snow <- weather_data$SNOW[88:280]
thunder <- weather_data$WT03[88:280] %>% 
  replace_na(0) %>% as.factor()


cones_real <- waffle_totals_daily$Cones[1:193]
bowls_real <- waffle_totals_daily$Bowls[1:193]
days_real <- waffle_totals_daily$Day[1:193] %>% as_factor()


firstmodel <- tibble(realdates,days_real,cones_real,bowls_real,dailytemp,dailyprecip,snow,thunder)

#Get gallery hop dates
gallery_hopdates <- firstmodel %>% 
  filter(days_real == 'Saturday') %>% 
  dplyr::select(realdates)
gallery_hopdates <- gallery_hopdates[10:27,]
gallery_hopdates <- gallery_hopdates[c(1,5,10,14,18),]
gallery_hop <- factor(rep('No', 193), levels = c('No', 'Yes'))
gallery_hop[c(69, 97, 132,160,188)] <-  'Yes'

#holidays
is_holiday <- factor(rep('No', 193), levels = c('No', 'Yes'))
is_holiday[c(7, 42, 64, 84, 98,162)] <-  'Yes'

firstmodel <- tibble(realdates,days_real,gallery_hop,is_holiday,cones_real,bowls_real,dailytemp,dailyprecip,snow,thunder)

cone_modelGLM <- glm.nb(formula = 
                   cones_real ~ days_real + dailyprecip + dailytemp + 
                   snow + thunder + gallery_hop + is_holiday, data = firstmodel)

bowl_modelGLM <- glm.nb(formula = 
                          bowls_real ~ days_real + dailyprecip + dailytemp + 
                          snow + thunder + gallery_hop + is_holiday, data = firstmodel,)

  
cones_function <- function(a,b,c,d,e){
    
    a <- readline('What day of the week is it? ')
    b <- readline('How much is it going to rain? (in) ')
    c <- readline('What is the average temp for the day? ')
    d <- readline('Is it gallery hop? ')
    e <- readline('Is it a holiday or holiday weekend? ')
    
    b <- as.numeric(paste(b))
    c <- as.numeric(paste(c))
    
    
conepredict <- round(predict(cone_modelGLM, data.frame(days_real = a, 
                                               dailyprecip = b, 
                                               dailytemp = c, 
                                               snow = 0, 
                                               thunder = '0', 
                                               gallery_hop = d, 
                                               is_holiday = e), 
                     type = 'response'))

bowlpredict <- round(predict(bowl_modelGLM, data.frame(days_real = a, 
                                        dailyprecip = b, 
                                        dailytemp = c, 
                                        snow = 0, 
                                        thunder = '0', 
                                        gallery_hop = d, 
                                        is_holiday = e), 
              type = 'response'))

predictions <- tibble(conepredict,bowlpredict) %>% add_column(.before = 'bowlpredict', 
                                                              'uppercones' = round(
                                                                1.10*conepredict)) %>% 
                                                  add_column(.after = 'bowlpredict', 
                                                              'upperbowls' = round(
                                                               1.10*bowlpredict))
print(predictions)

}

```

```{r Setting this up for re-use}

save(firstmodel, file = "data_for_waffle_model_updated10-10.Rdata")

```

```{r Using the Code Day-to-Day}

load("/Users/jacksonrudoff/Documents/Data Projects/Waffle Project/data_for_waffle_model_updated10-10.Rdata")

cone_modelGLM <- glm.nb(formula = 
                   cones_real ~ days_real + dailyprecip + dailytemp + 
                   snow + thunder + gallery_hop + is_holiday, data = firstmodel)

bowl_modelGLM <- glm.nb(formula = 
                          bowls_real ~ days_real + dailyprecip + dailytemp + 
                          snow + thunder + gallery_hop + is_holiday, data = firstmodel,)

  
cones_function <- function(a,b,c,d,e){
    
    a <- readline('What day of the week is it? ')
    b <- readline('How much is it going to rain? (in) ')
    c <- readline('What is the average temp for the day? ')
    d <- readline('Is it gallery hop? ')
    e <- readline('Is it a holiday or holiday weekend? ')
    
    b <- as.numeric(paste(b))
    c <- as.numeric(paste(c))
    
    
conepredict <- round(predict(cone_modelGLM, data.frame(days_real = a, 
                                               dailyprecip = b, 
                                               dailytemp = c, 
                                               snow = 0, 
                                               thunder = '0', 
                                               gallery_hop = d, 
                                               is_holiday = e), 
                     type = 'response'))

bowlpredict <- round(predict(bowl_modelGLM, data.frame(days_real = a, 
                                        dailyprecip = b, 
                                        dailytemp = c, 
                                        snow = 0, 
                                        thunder = '0', 
                                        gallery_hop = d, 
                                        is_holiday = e), 
              type = 'response'))

overflowcone <- 0.5*sd(firstmodel$cones_real)
overflowbowl <- 0.5*sd(firstmodel$bowls_real)

predictions <- tibble(conepredict,bowlpredict) %>% add_column(.before = 'bowlpredict', 
                                                              'uppercones' = round(
                                                                overflowcone+conepredict)) %>% 
                                                  add_column(.after = 'bowlpredict', 
                                                              'upperbowls' = 
                                                               round(overflowbowl+bowlpredict))
                                                      
print(predictions)

}


```

```{r Updating the model}

new_waffle_totals_daily <- read.xlsx("~/Documents/Data Projects/Waffle Project/waffle_totals.xlsx") %>% as_tibble() %>% dplyr::select(-X4)


weather_data <- read_csv("weather data.csv") %>% as_tibble()
weather_data <- weather_data[c(1:210, 617:810),]

dailytemp <- weather_data$TAVG
realdates <- weather_data$DATE
dailyprecip <- weather_data$PRCP
snow <- weather_data$SNOW
thunder <- weather_data$WT03 %>% 
  replace_na(0) %>% as.factor()


cones_real <- new_waffle_totals_daily$Cones[1:404]
bowls_real <- new_waffle_totals_daily$Bowls[1:404]
days_real <- new_waffle_totals_daily$Day[1:404] %>% as_factor()


newmodel <- tibble(realdates,days_real,cones_real,bowls_real,dailytemp,dailyprecip,snow,thunder)

#Get gallery hop dates
gallery_hopdates <- newmodel %>% 
  filter(days_real == 'Saturday') %>% 
  dplyr::select(realdates)
gallery_hopdates <- gallery_hopdates[c(2,7,11,15,20,24,28,40,44,49,53,57),]
gallery_hop <- factor(rep('No', 404), levels = c('No', 'Yes'))
gallery_hop[c(13, 48, 76, 104, 139, 167, 195, 279, 307, 342, 370, 398)] <-  'Yes'

#holidays
is_holiday <- factor(rep('No', 404), levels = c('No', 'Yes'))
is_holiday[c(43, 158, 183, 208, 210, 217, 252, 274, 294, 308, 372)] <-  'Yes'

newmodel <- tibble(realdates,days_real,gallery_hop,is_holiday,cones_real,bowls_real,dailytemp,dailyprecip,snow,thunder)

newmodel <- newmodel[!(newmodel$cones_real==0 & newmodel$bowls_real==0),]

#MODEL

cone_modelGLMnew <- glm.nb(formula = 
                   cones_real ~ days_real + dailyprecip + dailytemp + 
                   snow + thunder + gallery_hop + is_holiday, data = newmodel)

bowl_modelGLMnew <- glm.nb(formula = 
                          bowls_real ~ days_real + dailyprecip + dailytemp + 
                          snow + thunder + gallery_hop + is_holiday, data = newmodel)

#FUNCTION

cones_function_new <- function(a,b,c,d,e){
    
    a <- readline('What day of the week is it? ')
    b <- readline('How much is it going to rain? (in) ')
    c <- readline('What is the average temp for the day? ')
    d <- readline('Is it gallery hop? ')
    e <- readline('Is it a holiday or holiday weekend? ')
    
    b <- as.numeric(paste(b))
    c <- as.numeric(paste(c))
    
    
conepredict <- round(predict(cone_modelGLMnew, data.frame(days_real = a, 
                                               dailyprecip = b, 
                                               dailytemp = c, 
                                               snow = 0, 
                                               thunder = '0', 
                                               gallery_hop = d, 
                                               is_holiday = e), 
                     type = 'response'))

bowlpredict <- round(predict(bowl_modelGLMnew, data.frame(days_real = a, 
                                        dailyprecip = b, 
                                        dailytemp = c, 
                                        snow = 0, 
                                        thunder = '0', 
                                        gallery_hop = d, 
                                        is_holiday = e), 
              type = 'response'))

overflowcone <- 0.5*sd(firstmodel$cones_real)
overflowbowl <- 0.5*sd(firstmodel$bowls_real)

predictions <- tibble(conepredict,bowlpredict) %>% add_column(.before = 'bowlpredict', 
                                                              'uppercones' = round(
                                                                overflowcone+conepredict)) %>% 
                                                  add_column(.after = 'bowlpredict', 
                                                              'upperbowls' = 
                                                               round(overflowbowl+bowlpredict))
                                                      
print(predictions)

}

```



```{r For loop testing}
count <- 0
busy_days <- c()

for (i in seq_along(cones_real)) {
  
  if(cones_real[i] >= 140) {
  busy_days[i] <- cones_real[i] 
  }
  busy_days <- busy_days[!is.na(busy_days)]
}


```

